[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyC_de-W4MKr9QWJt3ViFTE5fj3D7e-vzIs"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "fitness-app-47f3f.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "fitness-app-47f3f"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "fitness-app-47f3f.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "843463635545"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:843463635545:web:b43b97cbd1a6919b6d3748"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-64FMHWDM85"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs" 